spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordenSoa?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Argentina/Cordoba
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ec2-18-215-154-77.compute-1.amazonaws.com
    port: 5672
    username: user
    password: password
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 10
          max-interval: 30000
          multiplier: 3.0

server:
  port: 8080
